const _ = {
    filter: require('lodash/filter'),
    map: require('lodash/map'),
    each: require('lodash/each'),
    find: require('lodash/find'),
    concat: require('lodash/concat'),
    max: require('lodash/max'),
    isEmpty: require('lodash/isEmpty'),
    cloneDeep: require('lodash/cloneDeep'),
    remove: require('lodash/remove'),
    reject: require('lodash/reject'),
    values: require('lodash/values'),
    reduce: require('lodash/reduce'),
    has: require('lodash/has'),
    isArray: require('lodash/isArray'),
    forEach: require('lodash/forEach'),
    isEqual: require('lodash/isEqual'),
    clone: require('lodash/clone'),
    orderBy: require('lodash/orderBy'),
    take: require('lodash/take'),
    padStart: require('lodash/padStart'),
    extend: require('lodash/extend'),
    sum: require('lodash/sum'),
    ary: require('lodash/ary'),
    isPlainObject: require('lodash/isPlainObject'),
    size: require('lodash/size'),
    join: require('lodash/join'),
    indexOf: require('lodash/indexOf'),
    last: require('lodash/last'),
    sortBy: require('lodash/sortBy'),
    uniqBy: require('lodash/uniqBy'),
    nth: require('lodash/nth'),
    without: require('lodash/without'),
    reverse: require('lodash/reverse'),
    first: require('lodash/first'),
    flatten: require('lodash/flatten'),
    findIndex: require('lodash/findIndex'),
    findKey: require('lodash/findKey'),
    uniq: require('lodash/uniq'),
    intersection: require('lodash/intersection'),
    keys: require('lodash/keys'),
    unionBy: require('lodash/unionBy'),
    sumBy: require('lodash/sumBy')
};

export default _;
